import { Box, Typography } from '@mui/material';
import Head from 'next/head';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<>
			<Head>
				<title>React Query</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box>
				<Navbar />
				<Typography variant='h1' color='initial'>
					this is the elemental index
				</Typography>
			</Box>
		</>
	);
}
